all:
  hosts:
    master:
      ansible_host: 192.168.10.100
      ip: 192.168.10.100
    worker1:
      ansible_host: 192.168.200.17
      ip: 192.168.200.17
    worker2:
      ansible_host: 192.168.100.17
      ip: 192.168.100.17
  children:
    kube_control_plane:
      hosts:
        master:
    kube_node:
      hosts:
        master:
        worker1:
        worker2:
    etcd:
      hosts:
        master:
        worker1:
        worker2:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}