all:
  hosts:
    node1:
      ansible_host: 192.168.200.23
      ip: 192.168.200.23
      access_ip: 192.168.200.23
    node2:
      ansible_host: 192.168.10.29
      ip: 192.168.10.29
      access_ip: 192.168.10.29
    node3:
      ansible_host: 192.168.100.22
      ip: 192.168.100.22
      access_ip: 192.168.100.22
  children:
    kube_control_plane:
      hosts:
        node1:
    kube_node:
      hosts:
        node1:
        node2:
        node3:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
